commands:
  daily: True
  beg: True
  fish: True
  hunt: True
  dig: True
  search: True
  highlow: True
  postmeme: True
  trivia: True

auto_buy:
  parent: True
  laptop: True
  shovel: True
  fishing pole: True
  hunting rifle: True
  
cooldowns:
  patron: False
  timeout: 5

logging:
  debug: True
  warning: True